"""add unique constraint to complete day table

Revision ID: 81c13c2a581b
Revises: 9aada5c58542
Create Date: 2024-06-02 15:11:57.136724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c13c2a581b'
down_revision: Union[str, None] = '9aada5c58542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_habit_date', 'complete_day', ['habit_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_habit_date', 'complete_day', type_='unique')
    # ### end Alembic commands ###
