"""add cascade delete habits to user table

Revision ID: fba85a7c9293
Revises: 6f2cd9dc280d
Create Date: 2024-06-14 12:43:03.654588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba85a7c9293'
down_revision: Union[str, None] = '6f2cd9dc280d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('habit_user_id_fkey', 'habit', type_='foreignkey')
    op.create_foreign_key(None, 'habit', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.create_foreign_key('habit_user_id_fkey', 'habit', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
