"""add 'created_at' column to habit table

Revision ID: 9aada5c58542
Revises: 97447f6bb2ff
Create Date: 2024-05-29 16:43:54.471777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aada5c58542'
down_revision: Union[str, None] = '97447f6bb2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'created_at')
    # ### end Alembic commands ###
