"""add foreign key to habit table

Revision ID: 77d4c6933045
Revises: ea139d5bbd6f
Create Date: 2024-05-26 21:33:09.050057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d4c6933045'
down_revision: Union[str, None] = 'ea139d5bbd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'habit', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.drop_column('habit', 'user_id')
    # ### end Alembic commands ###
