"""add cascade delete to habit table

Revision ID: 1b9e673be798
Revises: 7049674c035d
Create Date: 2024-06-08 17:22:16.707160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9e673be798'
down_revision: Union[str, None] = '7049674c035d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('complete_day_habit_id_fkey', 'complete_day', type_='foreignkey')
    op.create_foreign_key(None, 'complete_day', 'habit', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complete_day', type_='foreignkey')
    op.create_foreign_key('complete_day_habit_id_fkey', 'complete_day', 'habit', ['habit_id'], ['id'])
    # ### end Alembic commands ###
